"""Design tokens for Waldo Commander.

Generated by scripts/gen_tokens.py from design/tokens.json. Edit the spec and
regenerate rather than editing values here. ``theme.py`` turns these into
``--wc-*`` CSS variables, Quasar colour names and hex values for the 3D scene
and charts.
"""

from __future__ import annotations

THEMES = ("dark", "light")

# name -> theme -> CSS colour. A value of the form "{other}" aliases another token.
COLOR: dict[str, dict[str, str]] = {
    "scene-bg": {"dark": "oklch(14.5% 0 0)", "light": "#e0e0e0"},
    "scene-ground": {"dark": "oklch(30% 0 0)", "light": "#d4d4d4"},
    "scene-grid": {"dark": "oklch(55.6% 0 0)", "light": "oklch(43.9% 0 0)"},
    "scene-arm": {"dark": "#a3a3a3", "light": "#737373"},
    "scene-arm-sim": {"dark": "#c77d28", "light": "#c77d28"},
    "scene-arm-edit": {"dark": "#525252", "light": "#525252"},
    "scene-tool": {"dark": "#2a9d8f", "light": "#2a9d8f"},
    "scene-tool-moving": {"dark": "#4ecdc4", "light": "#4ecdc4"},
    "scene-tool-edit": {"dark": "#3d6b65", "light": "#3d6b65"},
    "scene-tool-moving-edit": {"dark": "#4d7e77", "light": "#4d7e77"},
    "scene-collision": {"dark": "#b00020", "light": "#b00020"},
    "scene-shape": {"dark": "#6d8ea0", "light": "#6d8ea0"},
    "scene-shape-draft": {"dark": "#9db8c8", "light": "#9db8c8"},
    "scene-shape-install": {"dark": "#55606a", "light": "#55606a"},
    "scene-shape-proposed": {"dark": "#8a7bb5", "light": "#8a7bb5"},
    "scene-hover": {"dark": "#ffffff", "light": "#ffffff"},
    "axis-x": {"dark": "#d94c3f", "light": "#d94c3f"},
    "axis-y": {"dark": "#2faf7a", "light": "#2faf7a"},
    "axis-z": {"dark": "#4a63e0", "light": "#4a63e0"},
    "axis-rx": {"dark": "#f1a79f", "light": "#f1a79f"},
    "axis-ry": {"dark": "#aee5cf", "light": "#aee5cf"},
    "axis-rz": {"dark": "#aeb9f3", "light": "#aeb9f3"},
    "axis-x-text": {"dark": "oklch(75.6% 0.145 28.7)", "light": "oklch(50.3% 0.179 28.7)"},
    "axis-y-text": {"dark": "oklch(72.2% 0.135 160.8)", "light": "oklch(47% 0.103 160.8)"},
    "axis-z-text": {"dark": "oklch(74.4% 0.130 270.3)", "light": "oklch(49.4% 0.192 270.3)"},
    "axis-rx-text": {"dark": "oklch(82.8% 0.089 26.1)", "light": "oklch(49.5% 0.120 28.7)"},
    "axis-ry-text": {"dark": "{axis-ry}", "light": "oklch(46.5% 0.100 160.8)"},
    "axis-rz-text": {"dark": "oklch(81.8% 0.083 276.0)", "light": "oklch(48.5% 0.120 270.3)"},
    "glass": {"dark": "oklch(37.1% 0 0 / 0.86)", "light": "oklch(98.5% 0 0 / 0.86)"},
    "glass-end": {"dark": "oklch(26.9% 0 0 / 0.86)", "light": "oklch(97% 0 0 / 0.86)"},
    "glass-border": {"dark": "oklch(97% 0 0 / 0.12)", "light": "oklch(20.5% 0 0 / 0.12)"},
    "well": {"dark": "oklch(20.5% 0 0 / 0.55)", "light": "oklch(92.2% 0 0 / 0.7)"},
    "scrim": {"dark": "oklch(0% 0 0 / 0.5)", "light": "oklch(20.5% 0 0 / 0.3)"},
    "state-hover": {"dark": "oklch(97% 0 0 / 0.08)", "light": "oklch(20.5% 0 0 / 0.06)"},
    "state-selected": {"dark": "oklch(97% 0 0 / 0.16)", "light": "oklch(20.5% 0 0 / 0.1)"},
    "text": {"dark": "oklch(97% 0 0)", "light": "oklch(20.5% 0 0)"},
    "text-muted": {"dark": "oklch(87% 0 0)", "light": "oklch(43.9% 0 0)"},
    "text-disabled": {"dark": "oklch(55.6% 0 0)", "light": "oklch(70.8% 0 0)"},
    "on-fill": {"dark": "oklch(98.5% 0 0)", "light": "oklch(98.5% 0 0)"},
    "on-bright": {"dark": "oklch(20.5% 0 0)", "light": "oklch(20.5% 0 0)"},
    "action": {"dark": "oklch(68.5% 0.169 237.323)", "light": "oklch(68.5% 0.169 237.323)"},
    "action-hover": {"dark": "oklch(58.8% 0.158 241.966)", "light": "oklch(58.8% 0.158 241.966)"},
    "action-text": {"dark": "oklch(90.1% 0.058 230.902)", "light": "oklch(44.3% 0.11 240.79)"},
    "focus-ring": {"dark": "oklch(74.6% 0.16 232.661)", "light": "{action}"},
    "control": {"dark": "oklch(43.9% 0 0)", "light": "oklch(87% 0 0)"},
    "progress": {"dark": "oklch(74.6% 0.16 232.661)", "light": "{action}"},
    "level-speed-lo": {"dark": "oklch(87.9% 0.169 91.605)", "light": "oklch(76.9% 0.188 70.08)"},
    "level-speed-hi": {"dark": "oklch(63.7% 0.237 25.331)", "light": "oklch(57.7% 0.245 27.325)"},
    "level-accel-lo": {"dark": "oklch(84.1% 0.238 128.85)", "light": "oklch(64.8% 0.2 131.684)"},
    "level-accel-hi": {"dark": "oklch(70.4% 0.14 182.503)", "light": "oklch(60% 0.118 184.704)"},
    "mode-sim": {"dark": "oklch(66.6% 0.179 58.318)", "light": "oklch(66.6% 0.179 58.318)"},
    "positive": {"dark": "oklch(90.5% 0.093 164.15)", "light": "oklch(43.2% 0.095 166.913)"},
    "positive-soft": {"dark": "oklch(76.5% 0.177 163.223 / 0.12)", "light": "oklch(50.8% 0.118 165.612 / 0.1)"},
    "warning": {"dark": "oklch(94.5% 0.129 101.54)", "light": "oklch(47.6% 0.114 61.907)"},
    "warning-fill": {"dark": "oklch(85.2% 0.199 91.936)", "light": "oklch(85.2% 0.199 91.936)"},
    "warning-soft": {"dark": "oklch(90.5% 0.182 98.111 / 0.1)", "light": "oklch(85.2% 0.199 91.936 / 0.22)"},
    "error": {"dark": "oklch(88.5% 0.062 18.334)", "light": "oklch(44.4% 0.177 26.899)"},
    "error-soft": {"dark": "oklch(70.4% 0.191 22.216 / 0.08)", "light": "oklch(50.5% 0.213 27.518 / 0.1)"},
    "info": {"dark": "{action-text}", "light": "{action-text}"},
    "run": {"dark": "oklch(69.6% 0.17 162.48)", "light": "oklch(69.6% 0.17 162.48)"},
    "estop": {"dark": "oklch(63.7% 0.237 25.331)", "light": "oklch(57.7% 0.245 27.325)"},
    "record": {"dark": "oklch(63.7% 0.237 25.331)", "light": "oklch(57.7% 0.245 27.325)"},
    "fill-positive": {"dark": "oklch(50.8% 0.118 165.612)", "light": "oklch(50.8% 0.118 165.612)"},
    "fill-warning": {"dark": "oklch(55.4% 0.135 66.442)", "light": "oklch(55.4% 0.135 66.442)"},
    "fill-error": {"dark": "oklch(50.5% 0.213 27.518)", "light": "oklch(50.5% 0.213 27.518)"},
    "ai-inspect": {"dark": "oklch(76.5% 0.177 163.223)", "light": "oklch(76.5% 0.177 163.223)"},
    "ai-inspect-text": {"dark": "oklch(84.5% 0.143 164.978)", "light": "oklch(43.2% 0.095 166.913)"},
    "ai-auto-edits": {"dark": "oklch(74.6% 0.16 232.661)", "light": "oklch(74.6% 0.16 232.661)"},
    "ai-auto-edits-text": {"dark": "oklch(90.1% 0.058 230.902)", "light": "oklch(44.3% 0.11 240.79)"},
    "ai-autopilot": {"dark": "oklch(70.2% 0.183 293.541)", "light": "oklch(70.2% 0.183 293.541)"},
    "ai-autopilot-text": {"dark": "oklch(89.4% 0.057 293.283)", "light": "oklch(49.1% 0.27 292.581)"},
    "measure-position": {"dark": "oklch(77.7% 0.152 181.912)", "light": "oklch(51.1% 0.096 186.391)"},
    "measure-current": {"dark": "oklch(83.3% 0.145 321.434)", "light": "oklch(51.8% 0.253 323.949)"},
    "path-cartesian": {"dark": "#10b981", "light": "oklch(50.8% 0.118 165.612)"},
    "path-joints": {"dark": "#2563eb", "light": "#2563eb"},
    "path-smooth": {"dark": "#a855f7", "light": "oklch(55.8% 0.288 302.321)"},
    "path-invalid": {"dark": "#ef4444", "light": "oklch(57.7% 0.245 27.325)"},
    "path-timing-warning": {"dark": "{warning-fill}", "light": "oklch(55.4% 0.135 66.442)"},
    "path-checkpoint": {"dark": "#94a3b8", "light": "#94a3b8"},
    "path-tool-action": {"dark": "{scene-tool}", "light": "{scene-tool}"},
    "physics-on-track": {"dark": "#59d973", "light": "oklch(52.7% 0.154 150.069)"},
    "physics-diverged": {"dark": "#f25940", "light": "oklch(57.7% 0.245 27.325)"},
    "physics-contact": {"dark": "#ff5d5d", "light": "oklch(57.7% 0.245 27.325)"},
    "physics-com": {"dark": "oklch(92.2% 0 0)", "light": "oklch(26.9% 0 0)"},
    "editor-exec-line": {"dark": "#ffff004d", "light": "#ffff004d"},
}

# name -> theme -> hex, for Three.js, ECharts and tests. Only opaque tokens;
# translucent ones (glass, well, soft tints, scrim) have no single hex.
COLOR_HEX: dict[str, dict[str, str]] = {
    "scene-bg": {"dark": "#0a0a0a", "light": "#e0e0e0"},
    "scene-ground": {"dark": "#2e2e2e", "light": "#d4d4d4"},
    "scene-grid": {"dark": "#737373", "light": "#525252"},
    "scene-arm": {"dark": "#a3a3a3", "light": "#737373"},
    "scene-arm-sim": {"dark": "#c77d28", "light": "#c77d28"},
    "scene-arm-edit": {"dark": "#525252", "light": "#525252"},
    "scene-tool": {"dark": "#2a9d8f", "light": "#2a9d8f"},
    "scene-tool-moving": {"dark": "#4ecdc4", "light": "#4ecdc4"},
    "scene-tool-edit": {"dark": "#3d6b65", "light": "#3d6b65"},
    "scene-tool-moving-edit": {"dark": "#4d7e77", "light": "#4d7e77"},
    "scene-collision": {"dark": "#b00020", "light": "#b00020"},
    "scene-shape": {"dark": "#6d8ea0", "light": "#6d8ea0"},
    "scene-shape-draft": {"dark": "#9db8c8", "light": "#9db8c8"},
    "scene-shape-install": {"dark": "#55606a", "light": "#55606a"},
    "scene-shape-proposed": {"dark": "#8a7bb5", "light": "#8a7bb5"},
    "scene-hover": {"dark": "#ffffff", "light": "#ffffff"},
    "axis-x": {"dark": "#d94c3f", "light": "#d94c3f"},
    "axis-y": {"dark": "#2faf7a", "light": "#2faf7a"},
    "axis-z": {"dark": "#4a63e0", "light": "#4a63e0"},
    "axis-rx": {"dark": "#f1a79f", "light": "#f1a79f"},
    "axis-ry": {"dark": "#aee5cf", "light": "#aee5cf"},
    "axis-rz": {"dark": "#aeb9f3", "light": "#aeb9f3"},
    "axis-x-text": {"dark": "#fe897a", "light": "#b4261e"},
    "axis-y-text": {"dark": "#44bf89", "light": "#066c47"},
    "axis-z-text": {"dark": "#8da7fe", "light": "#3b50cc"},
    "axis-rx-text": {"dark": "#fbb1a8", "light": "#9a4238"},
    "axis-ry-text": {"dark": "#aee5cf", "light": "#0c6a46"},
    "axis-rz-text": {"dark": "#b4bffa", "light": "#4559a2"},
    "text": {"dark": "#f5f5f5", "light": "#171717"},
    "text-muted": {"dark": "#d4d4d4", "light": "#525252"},
    "text-disabled": {"dark": "#737373", "light": "#a1a1a1"},
    "on-fill": {"dark": "#fafafa", "light": "#fafafa"},
    "on-bright": {"dark": "#171717", "light": "#171717"},
    "action": {"dark": "#00a6f4", "light": "#00a6f4"},
    "action-hover": {"dark": "#0084d1", "light": "#0084d1"},
    "action-text": {"dark": "#b8e6fe", "light": "#00598a"},
    "focus-ring": {"dark": "#00bcff", "light": "#00a6f4"},
    "control": {"dark": "#525252", "light": "#d4d4d4"},
    "progress": {"dark": "#00bcff", "light": "#00a6f4"},
    "level-speed-lo": {"dark": "#ffd230", "light": "#fe9a00"},
    "level-speed-hi": {"dark": "#fb2c36", "light": "#e7000b"},
    "level-accel-lo": {"dark": "#9ae600", "light": "#5ea500"},
    "level-accel-hi": {"dark": "#00bba7", "light": "#009689"},
    "mode-sim": {"dark": "#e17100", "light": "#e17100"},
    "positive": {"dark": "#a4f4cf", "light": "#006045"},
    "warning": {"dark": "#fff085", "light": "#894b00"},
    "warning-fill": {"dark": "#fdc700", "light": "#fdc700"},
    "error": {"dark": "#ffc9c9", "light": "#9f0712"},
    "info": {"dark": "#b8e6fe", "light": "#00598a"},
    "run": {"dark": "#00bc7d", "light": "#00bc7d"},
    "estop": {"dark": "#fb2c36", "light": "#e7000b"},
    "record": {"dark": "#fb2c36", "light": "#e7000b"},
    "fill-positive": {"dark": "#007a55", "light": "#007a55"},
    "fill-warning": {"dark": "#a65f00", "light": "#a65f00"},
    "fill-error": {"dark": "#c10007", "light": "#c10007"},
    "ai-inspect": {"dark": "#00d492", "light": "#00d492"},
    "ai-inspect-text": {"dark": "#5ee9b5", "light": "#006045"},
    "ai-auto-edits": {"dark": "#00bcff", "light": "#00bcff"},
    "ai-auto-edits-text": {"dark": "#b8e6fe", "light": "#00598a"},
    "ai-autopilot": {"dark": "#a684ff", "light": "#a684ff"},
    "ai-autopilot-text": {"dark": "#ddd6ff", "light": "#7008e7"},
    "measure-position": {"dark": "#00d5be", "light": "#00786f"},
    "measure-current": {"dark": "#f4a8ff", "light": "#a800b7"},
    "path-cartesian": {"dark": "#10b981", "light": "#007a55"},
    "path-joints": {"dark": "#2563eb", "light": "#2563eb"},
    "path-smooth": {"dark": "#a855f7", "light": "#9810fa"},
    "path-invalid": {"dark": "#ef4444", "light": "#e7000b"},
    "path-timing-warning": {"dark": "#fdc700", "light": "#a65f00"},
    "path-checkpoint": {"dark": "#94a3b8", "light": "#94a3b8"},
    "path-tool-action": {"dark": "#2a9d8f", "light": "#2a9d8f"},
    "physics-on-track": {"dark": "#59d973", "light": "#008236"},
    "physics-diverged": {"dark": "#f25940", "light": "#e7000b"},
    "physics-contact": {"dark": "#ff5d5d", "light": "#e7000b"},
    "physics-com": {"dark": "#e5e5e5", "light": "#262626"},
}

SPACE: dict[str, str] = {
    "space-1": "4px",
    "space-2": "8px",
    "space-3": "12px",
    "space-4": "16px",
}

RADIUS: dict[str, str] = {
    "radius-sm": "6px",
    "radius-md": "10px",
    "radius-pill": "9999px",
}

SIZE: dict[str, str] = {
    "size-control": "32px",
    "size-control-sm": "24px",
    "size-joint-bar": "33px",
    "size-jog-slot": "72px",
    "size-rail": "52px",
}

EFFECT: dict[str, str] = {
    "glass-blur": "36px",
    "glass-saturate": "150%",
}

OPACITY: dict[str, str] = {
    "opacity-disabled": "0.6",
    "opacity-locked": "0.15",
}

Z_INDEX: dict[str, str] = {
    "z-scene": "0",
    "z-loading": "10",
    "z-hud": "20",
    "z-panels": "30",
    "z-rail": "40",
    "z-rail-bottom": "50",
    "z-glow": "9998",
    "z-capsule": "9999",
}

DURATION: dict[str, str] = {
    "duration-instant": "40ms",
    "duration-fast": "150ms",
    "duration-base": "300ms",
    "duration-flash": "1500ms",
    "duration-ambient": "2600ms",
}

EASING: dict[str, str] = {
    "ease-enter": "ease-out",
    "ease-loop": "ease-in-out",
    "ease-pop": "cubic-bezier(0.34, 1.56, 0.64, 1)",
}

SHADOW: dict[str, dict[str, str]] = {
    "shadow-glass": {"dark": "inset -0.3px -1px 4px 0 rgba(0, 0, 0, 0.072), inset -1.5px 2.5px 0 -2px rgba(0, 0, 0, 0.108), inset 0 3px 4px -2px rgba(0, 0, 0, 0.108), 0 6px 16px 0 rgba(0, 0, 0, 0.048)", "light": "inset -0.3px -1px 4px 0 rgba(0, 0, 0, 0.144), inset -1.5px 2.5px 0 -2px rgba(0, 0, 0, 0.216), inset 0 3px 4px -2px rgba(0, 0, 0, 0.216), 0 6px 16px 0 rgba(0, 0, 0, 0.096)"},
}

FONT_FAMILY: dict[str, str] = {
    "sans": "Roboto, -apple-system, \"Helvetica Neue\", Helvetica, Arial, sans-serif",
    "mono": "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
}

# name -> (font-size, line-height, weight, letter-spacing or None)
TYPE_STYLE: dict[str, tuple[str, str, int, str | None]] = {
    "headline": ("20px", "28px", 600, None),
    "title": ("18px", "28px", 500, None),
    "label": ("14px", "20px", 500, None),
    "body": ("14px", "20px", 400, None),
    "caption": ("12px", "16px", 400, None),
    "micro": ("11px", "14px", 500, '0.02em'),
    "readout-lg": ("30px", "36px", 400, None),
    "readout": ("16px", "24px", 400, None),
    "code": ("13px", "20px", 400, None),
}
