"""Generate waldo_commander/common/tokens.py from design/tokens.json.

Run after any change to the design system's tokens.json:

    python scripts/gen_tokens.py

``COLOR_HEX`` holds only opaque tokens; translucent ones (glass, wells, soft
tints, scrim) have no single hex and are left out so ``hex_of`` fails loudly.
"""

from __future__ import annotations

import json
import math
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPEC = ROOT / "design" / "tokens.json"
OUT = ROOT / "waldo_commander" / "common" / "tokens.py"

_OKLCH = re.compile(
    r"oklch\(\s*([\d.]+)(%?)\s+([\d.]+)\s+([\d.]+)\s*(?:/\s*([\d.]+)(%?))?\s*\)"
)


def _oklch_to_srgb(L: float, C: float, h: float) -> tuple[float, float, float]:
    a = C * math.cos(math.radians(h))
    b = C * math.sin(math.radians(h))
    l_ = L + 0.3963377774 * a + 0.2158037573 * b
    m_ = L - 0.1055613458 * a - 0.0638541728 * b
    s_ = L - 0.0894841775 * a - 1.2914855480 * b
    lc, mc, sc = l_**3, m_**3, s_**3
    lin = (
        4.0767416621 * lc - 3.3077115913 * mc + 0.2309699292 * sc,
        -1.2684380046 * lc + 2.6097574011 * mc - 0.3413193965 * sc,
        -0.0041960863 * lc - 0.7034186147 * mc + 1.7076147010 * sc,
    )

    def enc(x: float) -> float:
        x = min(max(x, 0.0), 1.0)
        return 12.92 * x if x <= 0.0031308 else 1.055 * x ** (1 / 2.4) - 0.055

    return tuple(enc(c) for c in lin)  # type: ignore[return-value]


def parse(css: str) -> tuple[float, float, float, float]:
    """(r, g, b, a) in 0–1 from a hex or oklch() string."""
    css = css.strip()
    if css.startswith("#"):
        h = css[1:]
        if len(h) in (3, 4):
            h = "".join(ch * 2 for ch in h)
        rgb = tuple(int(h[i : i + 2], 16) / 255 for i in (0, 2, 4))
        alpha = int(h[6:8], 16) / 255 if len(h) == 8 else 1.0
        return (*rgb, alpha)  # type: ignore[return-value]
    m = _OKLCH.match(css)
    if not m:
        raise ValueError(f"unsupported colour syntax: {css}")
    L = float(m.group(1)) / (100 if m.group(2) else 1)
    rgb = _oklch_to_srgb(L, float(m.group(3)), float(m.group(4)))
    alpha = 1.0
    if m.group(5):
        alpha = float(m.group(5)) / (100 if m.group(6) else 1)
    return (*rgb, alpha)


def to_hex(rgba: tuple[float, float, float, float]) -> str:
    return "#" + "".join(f"{round(min(max(x, 0), 1) * 255):02x}" for x in rgba[:3])


def render(spec: dict) -> str:
    colors = spec["color"]["tokens"]
    by = {t["name"]: t["value"] for t in colors}

    def resolve(name: str, theme: str) -> str:
        v = by[name][theme]
        while v.startswith("{"):
            v = by[v[1:-1]][theme]
        return v

    out = [
        '"""Design tokens for Waldo Commander.',
        "",
        "Generated by scripts/gen_tokens.py from design/tokens.json. Edit the spec and",
        "regenerate rather than editing values here. ``theme.py`` turns these into",
        "``--wc-*`` CSS variables, Quasar colour names and hex values for the 3D scene",
        "and charts.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        'THEMES = ("dark", "light")',
        "",
        '# name -> theme -> CSS colour. A value of the form "{other}" aliases another token.',
        "COLOR: dict[str, dict[str, str]] = {",
    ]
    for t in colors:
        d, li = t["value"]["dark"], t["value"]["light"]
        out.append(f'    "{t["name"]}": {{"dark": "{d}", "light": "{li}"}},')
    out += [
        "}",
        "",
        "# name -> theme -> hex, for Three.js, ECharts and tests. Only opaque tokens;",
        "# translucent ones (glass, well, soft tints, scrim) have no single hex.",
        "COLOR_HEX: dict[str, dict[str, str]] = {",
    ]
    for t in colors:
        n = t["name"]
        rgba = {th: parse(resolve(n, th)) for th in ("dark", "light")}
        if any(v[3] < 1.0 for v in rgba.values()):
            continue
        out.append(
            f'    "{n}": {{"dark": "{to_hex(rgba["dark"])}", "light": "{to_hex(rgba["light"])}"}},'
        )
    out += ["}", ""]

    for section, var in (
        ("spacing", "SPACE"),
        ("radius", "RADIUS"),
        ("size", "SIZE"),
        ("effect", "EFFECT"),
        ("opacity", "OPACITY"),
        ("zIndex", "Z_INDEX"),
        ("duration", "DURATION"),
        ("easing", "EASING"),
    ):
        out.append(f"{var}: dict[str, str] = {{")
        for t in spec[section]["tokens"]:
            out.append(f'    "{t["name"]}": "{t["value"]}",')
        out += ["}", ""]

    sh = spec["shadow"]["tokens"][0]["value"]
    out += [
        "SHADOW: dict[str, dict[str, str]] = {",
        f'    "shadow-glass": {{"dark": "{sh["dark"]}", "light": "{sh["light"]}"}},',
        "}",
        "",
        "FONT_FAMILY: dict[str, str] = {",
    ]
    for k, v in spec["type"]["families"].items():
        out.append(f'    "{k}": {json.dumps(v)},')
    out += [
        "}",
        "",
        "# name -> (font-size, line-height, weight, letter-spacing or None)",
        "TYPE_STYLE: dict[str, tuple[str, str, int, str | None]] = {",
    ]
    for g in spec["type"]["groups"]:
        for s in g["styles"]:
            out.append(
                f'    "{s["name"]}": ("{s["fontSize"]}", "{s["lineHeight"]}", '
                f"{s['fontWeight']}, {s.get('letterSpacing')!r}),"
            )
    out += ["}", ""]
    return "\n".join(out)


def main(argv: list[str]) -> int:
    spec = json.loads(SPEC.read_text())
    text = render(spec)
    if "--check" in argv:
        if OUT.read_text() != text:
            print(f"{OUT.relative_to(ROOT)} is stale; run scripts/gen_tokens.py")
            return 1
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
